/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestApiRouteImport } from './routes/test-api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowsPfpRouteImport } from './routes/flows.pfp'

const TestApiRoute = TestApiRouteImport.update({
  id: '/test-api',
  path: '/test-api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsPfpRoute = FlowsPfpRouteImport.update({
  id: '/flows/pfp',
  path: '/flows/pfp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-api': typeof TestApiRoute
  '/flows/pfp': typeof FlowsPfpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-api': typeof TestApiRoute
  '/flows/pfp': typeof FlowsPfpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-api': typeof TestApiRoute
  '/flows/pfp': typeof FlowsPfpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test-api' | '/flows/pfp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-api' | '/flows/pfp'
  id: '__root__' | '/' | '/test-api' | '/flows/pfp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestApiRoute: typeof TestApiRoute
  FlowsPfpRoute: typeof FlowsPfpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-api': {
      id: '/test-api'
      path: '/test-api'
      fullPath: '/test-api'
      preLoaderRoute: typeof TestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/pfp': {
      id: '/flows/pfp'
      path: '/flows/pfp'
      fullPath: '/flows/pfp'
      preLoaderRoute: typeof FlowsPfpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestApiRoute: TestApiRoute,
  FlowsPfpRoute: FlowsPfpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
