/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedTestApiRouteImport } from './routes/_protected/test-api'
import { Route as ProtectedRoomsIndexRouteImport } from './routes/_protected/rooms.index'
import { Route as ProtectedGuestsIndexRouteImport } from './routes/_protected/guests.index'
import { Route as ProtectedGuestsGuestIdRouteImport } from './routes/_protected/guests.$guestId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTestApiRoute = ProtectedTestApiRouteImport.update({
  id: '/test-api',
  path: '/test-api',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRoomsIndexRoute = ProtectedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGuestsIndexRoute = ProtectedGuestsIndexRouteImport.update({
  id: '/guests/',
  path: '/guests/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGuestsGuestIdRoute = ProtectedGuestsGuestIdRouteImport.update({
  id: '/guests/$guestId',
  path: '/guests/$guestId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/test-api': typeof ProtectedTestApiRoute
  '/guests/$guestId': typeof ProtectedGuestsGuestIdRoute
  '/guests/': typeof ProtectedGuestsIndexRoute
  '/rooms/': typeof ProtectedRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/test-api': typeof ProtectedTestApiRoute
  '/guests/$guestId': typeof ProtectedGuestsGuestIdRoute
  '/guests': typeof ProtectedGuestsIndexRoute
  '/rooms': typeof ProtectedRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_protected/test-api': typeof ProtectedTestApiRoute
  '/_protected/guests/$guestId': typeof ProtectedGuestsGuestIdRoute
  '/_protected/guests/': typeof ProtectedGuestsIndexRoute
  '/_protected/rooms/': typeof ProtectedRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/test-api'
    | '/guests/$guestId'
    | '/guests/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/test-api'
    | '/guests/$guestId'
    | '/guests'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/sign-in'
    | '/sign-up'
    | '/_protected/test-api'
    | '/_protected/guests/$guestId'
    | '/_protected/guests/'
    | '/_protected/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/test-api': {
      id: '/_protected/test-api'
      path: '/test-api'
      fullPath: '/test-api'
      preLoaderRoute: typeof ProtectedTestApiRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/rooms/': {
      id: '/_protected/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof ProtectedRoomsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/guests/': {
      id: '/_protected/guests/'
      path: '/guests'
      fullPath: '/guests/'
      preLoaderRoute: typeof ProtectedGuestsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/guests/$guestId': {
      id: '/_protected/guests/$guestId'
      path: '/guests/$guestId'
      fullPath: '/guests/$guestId'
      preLoaderRoute: typeof ProtectedGuestsGuestIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedTestApiRoute: typeof ProtectedTestApiRoute
  ProtectedGuestsGuestIdRoute: typeof ProtectedGuestsGuestIdRoute
  ProtectedGuestsIndexRoute: typeof ProtectedGuestsIndexRoute
  ProtectedRoomsIndexRoute: typeof ProtectedRoomsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedTestApiRoute: ProtectedTestApiRoute,
  ProtectedGuestsGuestIdRoute: ProtectedGuestsGuestIdRoute,
  ProtectedGuestsIndexRoute: ProtectedGuestsIndexRoute,
  ProtectedRoomsIndexRoute: ProtectedRoomsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
