services:
  api:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - DOPPLER_TOKEN
    depends_on:
      - opensearch
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: unless-stopped
