import type { Room } from '@/components/rooms/RoomsList'

export const rooms: Array<Room> = [
  {
    id: '1',
    room_number: '101',
    floor: 1,
    room_type: 'Double Suite',
    tags: ['occupied'],
  },
  { id: '2', room_number: '102', floor: 1, room_type: 'Queen Suite' },
  {
    id: '3',
    room_number: '103',
    floor: 1,
    room_type: 'King Suite',
    tags: ['occupied', 'cleaning'],
  },
  { id: '4', room_number: '104', floor: 1, room_type: 'Queen Suite' },
  {
    id: '5',
    room_number: '105',
    floor: 1,
    room_type: 'Double Suite',
    tags: ['occupied'],
  },
  { id: '6', room_number: '106', floor: 1, room_type: 'Twin Suite' },
  {
    id: '7',
    room_number: '107',
    floor: 1,
    room_type: 'King Suite',
    tags: ['cleaning'],
  },
  {
    id: '8',
    room_number: '108',
    floor: 1,
    room_type: 'Queen Suite',
    tags: ['occupied'],
  },
  { id: '9', room_number: '109', floor: 1, room_type: 'Double Suite' },
  {
    id: '10',
    room_number: '110',
    floor: 1,
    room_type: 'Queen Suite',
    tags: ['occupied', 'cleaning'],
  },
  {
    id: '11',
    room_number: '201',
    floor: 2,
    room_type: 'King Suite',
    tags: ['occupied'],
  },
  { id: '12', room_number: '202', floor: 2, room_type: 'Queen Suite' },
  {
    id: '13',
    room_number: '203',
    floor: 2,
    room_type: 'Double Suite',
    tags: ['cleaning'],
  },
  {
    id: '14',
    room_number: '204',
    floor: 2,
    room_type: 'Twin Suite',
    tags: ['occupied'],
  },
  { id: '15', room_number: '205', floor: 2, room_type: 'Queen Suite' },
  {
    id: '16',
    room_number: '206',
    floor: 2,
    room_type: 'King Suite',
    tags: ['occupied'],
  },
  { id: '17', room_number: '207', floor: 2, room_type: 'Queen Suite' },
  {
    id: '18',
    room_number: '208',
    floor: 2,
    room_type: 'Double Suite',
    tags: ['occupied', 'cleaning'],
  },
  { id: '19', room_number: '209', floor: 2, room_type: 'Twin Suite' },
  {
    id: '20',
    room_number: '210',
    floor: 2,
    room_type: 'Queen Suite',
    tags: ['occupied'],
  },
  { id: '21', room_number: '301', floor: 3, room_type: 'Queen Suite' },
  {
    id: '22',
    room_number: '302',
    floor: 3,
    room_type: 'Double Suite',
    tags: ['occupied'],
  },
  { id: '23', room_number: '303', floor: 3, room_type: 'King Suite' },
  {
    id: '24',
    room_number: '304',
    floor: 3,
    room_type: 'Twin Suite',
    tags: ['cleaning'],
  },
  {
    id: '25',
    room_number: '305',
    floor: 3,
    room_type: 'Queen Suite',
    tags: ['occupied'],
  },
  { id: '26', room_number: '306', floor: 3, room_type: 'Queen Suite' },
  {
    id: '27',
    room_number: '307',
    floor: 3,
    room_type: 'Double Suite',
    tags: ['occupied'],
  },
  { id: '28', room_number: '308', floor: 3, room_type: 'King Suite' },
  {
    id: '29',
    room_number: '309',
    floor: 3,
    room_type: 'Twin Suite',
    tags: ['occupied', 'cleaning'],
  },
  { id: '30', room_number: '310', floor: 3, room_type: 'Queen Suite' },
  { id: '31', room_number: '401', floor: 4, room_type: 'Double Suite' },
  {
    id: '32',
    room_number: '402',
    floor: 4,
    room_type: 'King Suite',
    tags: ['occupied'],
  },
  {
    id: '33',
    room_number: '403',
    floor: 4,
    room_type: 'Queen Suite',
    tags: ['cleaning'],
  },
  { id: '34', room_number: '404', floor: 4, room_type: 'Twin Suite' },
  {
    id: '35',
    room_number: '405',
    floor: 4,
    room_type: 'Queen Suite',
    tags: ['occupied'],
  },
  { id: '36', room_number: '406', floor: 4, room_type: 'Double Suite' },
  {
    id: '37',
    room_number: '407',
    floor: 4,
    room_type: 'King Suite',
    tags: ['occupied'],
  },
  { id: '38', room_number: '408', floor: 4, room_type: 'Queen Suite' },
  {
    id: '39',
    room_number: '409',
    floor: 4,
    room_type: 'Twin Suite',
    tags: ['occupied', 'cleaning'],
  },
  { id: '40', room_number: '410', floor: 4, room_type: 'Queen Suite' },
  { id: '41', room_number: '501', floor: 5, room_type: 'King Suite' },
  {
    id: '42',
    room_number: '502',
    floor: 5,
    room_type: 'Queen Suite',
    tags: ['occupied'],
  },
  { id: '43', room_number: '503', floor: 5, room_type: 'Double Suite' },
  {
    id: '44',
    room_number: '504',
    floor: 5,
    room_type: 'Twin Suite',
    tags: ['cleaning'],
  },
  {
    id: '45',
    room_number: '505',
    floor: 5,
    room_type: 'Queen Suite',
    tags: ['occupied'],
  },
  { id: '46', room_number: '506', floor: 5, room_type: 'King Suite' },
  {
    id: '47',
    room_number: '507',
    floor: 5,
    room_type: 'Queen Suite',
    tags: ['occupied'],
  },
  {
    id: '48',
    room_number: '508',
    floor: 5,
    room_type: 'Double Suite',
    tags: ['occupied', 'cleaning'],
  },
  { id: '49', room_number: '509', floor: 5, room_type: 'Twin Suite' },
  {
    id: '50',
    room_number: '510',
    floor: 5,
    room_type: 'Queen Suite',
    tags: ['occupied'],
  },
]
